[package]
name = "test_project"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.11.2"
scarb-version = "2.11.3"

[dependencies]
starknet = "2.11.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", branch = "main" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
