[package]
name = "test_project"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.15.0"
scarb-version = "2.15.1"

[dependencies]
assert_macros = "2.15.1"
starknet = "2.15.1"
# TODO: Update this once OpenZeppelin Contracts for Cairo v4.0.0-alpha.0 is released
openzeppelin_macros = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_account = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_finance = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_governance = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_security = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_upgrades = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
