[package]
name = "test_project"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.13.1"
scarb-version = "2.13.1"

[dependencies]
assert_macros = "2.13.1"
starknet = "2.13.1"
openzeppelin_macros = "3.0.0"
openzeppelin_access = "3.0.0"
openzeppelin_account = "3.0.0"
openzeppelin_finance = "3.0.0"
openzeppelin_interfaces = "2.1.0"
openzeppelin_governance = "3.0.0"
openzeppelin_introspection = "3.0.0"
openzeppelin_security = "3.0.0"
openzeppelin_token = "3.0.0"
openzeppelin_upgrades = "3.0.0"
openzeppelin_utils = "2.1.0"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
