[package]
name = "test_project"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.12.0"
scarb-version = "2.12.0"

[dependencies]
starknet = "2.12.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v2.0.0" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
